addpath('/scratch/braindata/kauttoj2/Memento/2015/analysis/memento_git_project/Misc');
VIDEO_FILES.FIRST={...
    '/scratch/braindata/kauttoj2/Memento/2015/Stimulus/Memento3part_run1.avi',...
    '/scratch/braindata/kauttoj2/Memento/2015/Stimulus/Memento3part_run2.avi',...
    '/scratch/braindata/kauttoj2/Memento/2015/Stimulus/Memento3part_run3.avi'};
VIDEO_FILES.SECOND=VIDEO_FILES.FIRST;
frame_plotter('memento_loop_keyframe_timings_FINAL.txt',VIDEO_FILES,'memento_loop_keyframes');