clear VIDEO_FILES
addpath('/scratch/braindata/kauttoj2/Memento/2015/analysis/memento_git_project/Misc');
VIDEO_FILES.FIRST={...
    '/scratch/braindata/kauttoj2/Memento/2015/Stimulus/Memento3part_run1.avi',...
    '/scratch/braindata/kauttoj2/Memento/2015/Stimulus/Memento3part_run2.avi',...
    '/scratch/braindata/kauttoj2/Memento/2015/Stimulus/Memento3part_run3.avi'};
VIDEO_FILES.SECOND={...
    '/scratch/braindata/kauttoj2/Memento/2015/Stimulus/M1_chrono_checkAudio_Mjpeg_April2015.avi',...
    '/scratch/braindata/kauttoj2/Memento/2015/Stimulus/M2_chronological_stimuls_april2015.avi',...
    '/scratch/braindata/kauttoj2/Memento/2015/Stimulus/M3_chronological_stimuls_april2015.avi'};
frame_plotter('memento_chrono_original_color_timings_FINAL.txt',VIDEO_FILES,'memento_color_segments');